/** @deprecated Import from `@/lib/auth/authz` — kept for compatibility. */
export {
  AuthorizationError,
  getCurrentUser,
  requireCurrentUser,
  canManageOrganizationPolicy,
  canViewBilling,
  canManageBillingSpend,
  canManageInvitations,
  canRenameWorkspace,
  getMembershipForCurrentUser,
  requireOrgAdmin,
  requireOrgOwner,
  requirePlatformOperator,
  requirePlatformSuperAdmin,
  requireVerifiedForAiSpend,
  isPlatformOperator,
  isPlatformSuperAdmin,
  canMutatePlatform,
  canEditTransactionalTemplates,
} from "@/lib/auth/authz";
