ALTER TYPE "EmailLength" RENAME VALUE 'ONE_PARAGRAPH' TO 'SHORT';
ALTER TYPE "EmailLength" RENAME VALUE 'TWO_PARAGRAPH' TO 'MEDIUM';
ALTER TYPE "EmailLength" RENAME VALUE 'THREE_PARAGRAPH' TO 'LONG';

ALTER TABLE "Campaign"
  ALTER COLUMN "emailLength" SET DEFAULT 'MEDIUM';
